nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "pi.local"
    root: "/var/www/demo/application/htdocs"
    index: "index.php lean.php index.html index.htm"
#    error_page: ""
#    access_log: ""
#    error_log: ""
    extra_parameters: |
      location /lean.php {
        try_files $uri $uri/ /lean.php$is_args$args;
      }

      location / {
          try_files $uri $uri/ /index.php$is_args$args;
      }

      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_read_timeout 600s;
        fastcgi_send_timeout 600s;
      }
