parameters:
    baseDataDirectory: "/data"

services:
    userRepository:
        class: UserRepository
        arguments: ["@db"]

    userService:
        class: UserService
        arguments: ["%baseDataDirectory%/user"]

    db:
        synthetic: true
